<?php
//$Id$

/**
*  hook_menu implementation
*
*/
function fieldswitch_menu() {
  $items = array();
  $items['fswitch/all'] = array(
    'title' => 'Перенести поле складів',
    'page callback' => 'fieldswitch_switch_fields',
    'access callback' => 'user_access',
	'access arguments' => array('fswitch field settings'),
    'type' => MENU_NORMAL_ITEM,  
  );
  return $items;
}

/**
* hook_permission() implementation
*
*/
function fieldswitch_permission() {
  $permissions = array(
    'fswitch field settings' => array(
	  'title' => t('Автоматично встановлювати параметри відображення обраного поля'),
	  'description' => t('Надає доступ до равтоматичної заміни параметрів відображення обраного поля відносно іншого поля у всіх обраних типах контенту.'),
	 ),
  );
  return $permissions;
}

/**
*  Switch field settings main handler
*/
function fieldswitch_switch_fields() {
  $entity_type = 'node';
  $view_mode = 'default';
  $source = 'field_product_availability';
  $dest = 'field_product_store_relation';
  $bundles = fieldswitch_get_content_types($dest);
  
  //walk for product bundles
  foreach ($bundles as $bundle) {
    	
	$old_layout = ds_get_layout($entity_type, $bundle, $view_mode, FALSE);
	$all_layouts = ds_get_layout_info();
	$new_layout_key = 'ktc_product_2col';
	$new_layout = $all_layouts['ktc_product_2col'];
	
	/*
	* Mapping settings must be here
	*/
	
	// Create new record.
    $record = new stdClass();
    $record->id = $entity_type . '|' . $bundle . '|' . $view_mode;;
    $record->entity_type = $entity_type;
    $record->bundle = $bundle;
    $record->view_mode = $view_mode;
    $record->layout = $new_layout_key;
    $record->settings = $old_layout['settings'];
    unset($record->settings['regions']);
    unset($record->settings['fields']);
	
	//Remapping
	
		
	dsm($all_layouts);
  }

  
  return "1111";
}

/**
* Get product content types by source field name
* Input parameters: field name string
* Result: associative array of product content types
*
*/
function fieldswitch_get_content_types($fieldname) {
  if (isset($fieldname)) {
    $field_settings = field_info_field($fieldname);
	if (isset($field_settings['bundles']['node'])) return $field_settings['bundles']['node']; else return NULL;
  }
}


