<?php
//$Id$

/**
*  hook_menu implementation
*
*/
function fieldswitch_menu() {
  $items = array();
  $items['fswitch/all'] = array(
    'title' => 'Перенести поле складів',
    'page callback' => 'fieldswitch_switch_fields',
    'access callback' => 'user_access',
	'access arguments' => array('fswitch field settings'),
    'type' => MENU_NORMAL_ITEM,  
  );
  return $items;
}

/**
* hook_permission() implementation
*
*/
function fieldswitch_permission() {
  $permissions = array(
    'fswitch field settings' => array(
	  'title' => t('Автоматично встановлювати параметри відображення обраного поля'),
	  'description' => t('Надає доступ до равтоматичної заміни параметрів відображення обраного поля відносно іншого поля у всіх обраних типах контенту.'),
	 ),
  );
  return $permissions;
}

/**
*  Switch field settings main handler
*/
function fieldswitch_switch_fields() {
  dsm(fieldswitch_get_content_types());
  return "1111";
}

/**
* Get product content types by present product csv files for import
* Input parameters: none
* Result: associative array of product content types
*
*/
function fieldswitch_get_content_types() {
  $path = variable_get('parser_csv_import_folder','');
  $fls = glob($path.'/*.csv');
  
  foreach ($fls as $fl) {
    $fl = str_replace($path.'/', '', $fl);
	$fl = str_replace('.csv', '', $fl);
	$filelist[] = $fl;
  }
  
  unset($fls, $fl);
 return $filelist;	
}

